reference_data:
  path: D:\Research\Phosphine-Ligands\Data\Riv-2-25\input-data-builder-v2.xlsx
  sheet_name: 'input'
reference_color: '#ffc75f'
screening_data: 
  path: D:\Research\Phosphine-Ligands\Data\Riv-2-25\virtual_screen_in.xlsx
  sheet_name: 'in'
screening_color: '#ff5e78'
descriptors_to_use:                   # from Jackson's analysis
  - L
  - B1
  - B5
  - buried volume
  - all frags P Mulliken Charge
  - all frags HOMO-LUMO Gap
  - all frags P NMR Shielding