xl_file: D:\Research\Phosphine-Ligands\Data\Riv-2-25\input-data-builder-v2.xlsx
target_column: bmi
descrptr_columns:
  - L
  - B1
  - B5
  - buried volume
  - all frags P Mulliken Charge
  - all frags HOMO-LUMO Gap
  - all frags P NMR Shielding
output_directory: D:\Research\Phosphine-Ligands\Data\Riv-2-25