X: D:\Research\Phosphine-Ligands\Data\Riv-2-25\X.p
y: D:\Research\Phosphine-Ligands\Data\Riv-2-25\n1m2\y_n1m2.p
descriptor_names: D:\Research\Phosphine-Ligands\Data\Riv-2-25\descriptor_names.p
output_dir: D:\Research\Phosphine-Ligands\Data\Riv-2-25\n1m2
response: n1m2
proportion_of_dataset_for_seeding: 0.05
random_seed: 42
n_optimization_steps: 80
acquisition_function:
  label: ucb
  hyperparameters:
    beta: 100.