X: D:\Research\Phosphine-Ligands\Data\Riv-2-25\X.p
y: D:\Research\Phosphine-Ligands\Data\Riv-2-25\y.p
acquisition_function: expected_improvement
descriptor_names: D:\Research\Phosphine-Ligands\Data\Riv-2-25\descriptor_names.p
output_dir: D:\Research\Phosphine-Ligands\Data\Riv-2-25
response: bmi
proportion_of_dataset_for_seeding: 0.05
random_seed: 42
n_optimization_steps: 2
visualization_dim: 0